# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- powershell: |
    Write-Host "Creating timestamp for build artifact"
    $now=$(Get-Date -Format dd_MM_yyyy-HH_mm)
    Write-Host "##vso[task.setvariable variable=timestamp]$now"
  displayName: "Creating build timestamp"

- script: |
    yarn init
  displayName: 'Install dependencies'

- script: |
    yarn dist:browser
  displayName: "Build dist"
  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(artifactName).zip'
    replaceExistingArchive: true
  displayName: "Archive dist for artificat publishing"

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(artifactName)'
    publishLocation: 'Container'
  displayName: "Publish build artifact"